#  특정 년생에 대한 분석 - 여자

```{r warning=FALSE, echo=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)
library(here)           # file pathways
source(here::here("_common", "common.R"))
source(here::here("_common", "preprocess.R"))
```


## 자료 읽기

```{r}
dirpath <- here("data","feather","paps_mean.feather")
df_sch_mean <- read_feather(dirpath, col_select = NULL, as_data_frame = TRUE, mmap = TRUE)
df_sch_mean <- df_sch_mean %>% dplyr::filter(`년도` >= 2011 ) 
df_sch_mean$`년도` <-  factor(df_sch_mean$`년도`)
```


## 나이그룹 지정과 통계량 계산

- 초등학교 5학년의 나이를 11세로 지정
- 생년(birth year) = 관측년도 - 관측시 나이 
   + 예를 들어 2011년에 초등_5학년인 경우 2011 - 11 = 2000년생
   
```{r}
#| echo: false
#| warning: false

a01 <- df_sch_mean %>%
  dplyr::filter( `성별` == "여성") %>% 
  group_by(`선택종목`, `년도`, `학교_학년`) %>% 
    summarize( 전국평균 = weighted.mean(`평균`,`학생수`),.groups = 'drop') %>%
    dplyr::filter(!is.na(학교_학년))

birthyear <- a01  %>% 
    mutate(생년 = case_when(
        `학교_학년` == "초등학교_5" ~ 2010  + as.numeric(년도) -11,
        `학교_학년` == "초등학교_6" ~ 2010  + as.numeric(년도) - 12,
        `학교_학년` == "중학교_1" ~ 2010  + as.numeric(년도) - 13,
        `학교_학년` == "중학교_2" ~ 2010  + as.numeric(년도) - 14,
        `학교_학년` == "중학교_3" ~ 2010  + as.numeric(년도) - 15,
        `학교_학년` == "고등학교_1" ~ 2010  + as.numeric(년도) - 16,
        `학교_학년` == "고등학교_2" ~ 2010  + as.numeric(년도) - 17,
        `학교_학년` == "고등학교_3" ~ 2010  + as.numeric(년도) - 18,
        .default =NA )) %>%
    dplyr::mutate(생년 = factor(생년)) %>%
    dplyr::select(-`년도`) %>%
    dplyr::relocate(생년, .before = `학교_학년`) %>%
    dplyr::arrange(`선택종목`, `생년`, `학교_학년`) %>%
    dplyr::filter(생년 %in% c("2000","2001","2002","2003","2004"))#,"2005","2006","2007","2008","2009"))


birthyear_w<- birthyear %>%  pivot_wider(names_from = `학교_학년`, values_from = 전국평균) 

write.xlsx(birthyear_w, file = here("data","outputs","birthyear_item_mean_female.xlsx"))

  

```

## 종목별 비교

### 심폐지구력

```{r}
#| echo: false
#| warning: false

tvar <- test_item_levels[1]
res <- summ_by_birthyear(birthyear,birthyear_w,tvar,"여성" )
res[[1]]
res[[2]]
```

```{r}
#| echo: false
tvar <- test_item_levels[2]
res <- summ_by_birthyear(birthyear,birthyear_w,tvar,"여성" )
res[[1]]
res[[2]]
```


```{r}
#| echo: false
tvar <- test_item_levels[3]
res <- summ_by_birthyear(birthyear,birthyear_w,tvar ,"여성")
res[[1]]
res[[2]]
```

### 유연성

```{r}
#| echo: false
tvar <- test_item_levels[4]
res <- summ_by_birthyear(birthyear,birthyear_w,tvar ,"여성")
res[[1]]
res[[2]]
```

```{r}
#| echo: false
tvar <- test_item_levels[5]
res <- summ_by_birthyear(birthyear,birthyear_w,tvar ,"여성")
res[[1]]
res[[2]]
```

### 근력

```{r}
#| echo: false
tvar <- test_item_levels[6]
res <- summ_by_birthyear(birthyear,birthyear_w,tvar ,"여성")
res[[1]]
res[[2]]
```

```{r}
#| echo: false
tvar <- test_item_levels[7]
res <- summ_by_birthyear(birthyear,birthyear_w,tvar ,"여성")
res[[1]]
res[[2]]
```

```{r}
#| echo: false
tvar <- test_item_levels[8]
res <- summ_by_birthyear(birthyear,birthyear_w,tvar,"여성" )
res[[1]]
res[[2]]
```


### 순발력

```{r}
#| echo: false
tvar <- test_item_levels[9]
res <- summ_by_birthyear(birthyear,birthyear_w,tvar,"여성" )
res[[1]]
res[[2]]
```

```{r}
#| echo: false
tvar <- test_item_levels[10]
res <- summ_by_birthyear(birthyear,birthyear_w,tvar ,"여성")
res[[1]]
res[[2]]
```


### 신체 구성

```{r}
#| echo: false
tvar <- test_item_levels[11]
res <- summ_by_birthyear(birthyear,birthyear_w,tvar ,"여성")
res[[1]]
res[[2]]
```

```{r}
#| echo: false
tvar <- test_item_levels[12]
res <- summ_by_birthyear(birthyear,birthyear_w,tvar ,"여성")
res[[1]]
res[[2]]
```


```{r}
#| echo: false
tvar <- test_item_levels[13]
res <- summ_by_birthyear(birthyear,birthyear_w,tvar ,"여성")
res[[1]]
res[[2]]
```
