# PAPS의 체력항목 분석 - 심폐지구력


```{r warning=FALSE, echo=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)
library(here)           # file pathways
source(here::here("_common", "common.R"))
source(here::here("_common", "preprocess.R"))
```


## PAPS의 체력항목 - 심폐지구력

### 자료 읽기

```{r}
dirpath <- here("data","feather","paps_mean.feather")
df_sch_mean <- read_feather(dirpath, col_select = NULL, as_data_frame = TRUE, mmap = TRUE)
df_sch_mean <- df_sch_mean %>% dplyr::filter(`년도` >= 2011 ) 
df_sch_mean$`년도` <-  factor(df_sch_mean$`년도`)
```


### 스텝검사 - 남자


```{r}
res <- summ_stat_plot_itemwise_sex_all(df_sch_mean, "스텝검사", "남성", "chap2")
res[[1]]
res[[2]]
```

```{r results='asis'}
if(isword) cat("\n", wordnewpage, "\n")
```

### 스텝검사 - 여자

```{r}
res <- summ_stat_plot_itemwise_sex_all(df_sch_mean, "스텝검사", "여성", "chap2")
res[[1]]
res[[2]]
```

```{r results='asis'}
if(isword) cat("\n", wordnewpage, "\n")
```

### 오래달리기걷기 - 남자


```{r}
res <- summ_stat_plot_itemwise_sex_all(df_sch_mean, "오래달리기걷기", "남성", "chap2")
res[[1]]
res[[2]]
```

```{r results='asis'}
if(isword) cat("\n", wordnewpage, "\n")
```

### 오래달리기걷기 - 여자

```{r}
res <- summ_stat_plot_itemwise_sex_all(df_sch_mean, "오래달리기걷기", "여성", "chap2")
res[[1]]
res[[2]]
```

```{r results='asis'}
if(isword) cat("\n", wordnewpage, "\n")
```

### 왕복오래달리기 - 남자


```{r}
res <- summ_stat_plot_itemwise_sex_all(df_sch_mean, "왕복오래달리기", "남성", "chap2")
res[[1]]
res[[2]]
```

```{r results='asis'}
if(isword) cat("\n", wordnewpage, "\n")
```

### 왕복오래달리기 - 여자

```{r}
res <- summ_stat_plot_itemwise_sex_all(df_sch_mean, "왕복오래달리기", "여성", "chap2")
res[[1]]
res[[2]]
```

```{r results='asis'}
if(isword) cat("\n", wordnewpage, "\n")
```