# 학교별 평균자료 생성

render 하지 말고 project  를 로딩한 후 source 로 실행맇 것 

```{r warning=FALSE, echo=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)
library(here)           # file pathways
source(here::here("_common", "common.R"))
source(here::here("_common", "preprocess.R"))
```


## 종목 선택 현황 - 심폐지구력 

### 초등학교 

```{r}
res_e_1 <- summ_by_school_3var(df_e_01, SHLR_NTS, MIN_SEC_LRW_HR, PEI_NMVL, "초등학교", "심폐지구력")
res_e_2 <- summ_by_school_2var(df_e_01, BKRCH_NMVL, GNRLZ_FLX_NMVL, "초등학교", "유연성")
res_e_3 <- summ_by_school_3var(df_e_01, PSP_NTS, CLUP_NTS, GRIP_NMVL, "초등학교", "근지구력")
res_e_4 <- summ_by_school_2var(df_e_01, R50M_REC_HR, SLJ_NMVL, "초등학교", "순발력")
```

```{r}
res_e_1 <- res_e_1 %>% dplyr::filter(`학년` >= 5)   # 5학년 이상
res_e_2 <- res_e_2 %>% dplyr::filter(`학년` >= 5)   # 5학년 이상
res_e_3 <- res_e_3 %>% dplyr::filter(`학년` >= 5)   # 5학년 이상
res_e_4 <- res_e_4 %>% dplyr::filter(`학년` >= 5)   # 5학년 이상
```


### 중학교 

```{r}
res_m_1 <- summ_by_school_3var(df_m_01, SHLR_NTS, MIN_SEC_LRW_HR, PEI_NMVL, "중학교", "심폐지구력")
res_m_2 <- summ_by_school_2var(df_m_01, BKRCH_NMVL, GNRLZ_FLX_NMVL, "중학교", "유연성")
res_m_3 <- summ_by_school_3var(df_m_01, PSP_NTS, CLUP_NTS, GRIP_NMVL, "중학교", "근지구력")
res_m_4 <- summ_by_school_2var(df_m_01, R50M_REC_HR, SLJ_NMVL, "중학교", "순발력")
```

###고등학교 


```{r}
res_h_1 <- summ_by_school_3var(df_h_01, SHLR_NTS, MIN_SEC_LRW_HR, PEI_NMVL, "고등학교", "심폐지구력")
res_h_2 <- summ_by_school_2var(df_h_01, BKRCH_NMVL, GNRLZ_FLX_NMVL, "고등학교", "유연성")
res_h_3 <- summ_by_school_3var(df_h_01, PSP_NTS, CLUP_NTS, GRIP_NMVL, "고등학교", "근지구력")
res_h_4 <- summ_by_school_2var(df_h_01, R50M_REC_HR, SLJ_NMVL, "고등학교", "순발력")
```

## 최종 자료
```{r}
res_e <- rbind(res_e_1, res_e_2, res_e_3, res_e_4)
res_m <- rbind(res_m_1, res_m_2, res_m_3, res_m_4)
res_h <- rbind(res_h_1, res_h_2, res_h_3, res_h_4)
data_for_save1 <- rbind(res_e, res_m, res_h)
write_feather(data_for_save1, here("data","feather","paps_mean.feather"))
rm(list = ls())